const Router = require("express")
const router = new Router()
const basketRouter = require("./BasketRouter")
const bikeRouter = require("./BikeRouter")
const categoryBikeRouter = require("./CategoryBikeRouter")
const categoryServiceRouter = require("./CategoryServiceRouter")
const orderBikeRouter = require("./OrderBikeRouter")
const orderPartRouter = require("./OrderPartRouter")
const orderServiceRouter = require("./OrderServiceRouter")
const partRouter = require("./PartRouter")
const serviceRouter = require("./ServiceRouter")
const typeBikeRouter = require("./TypeBikeRouter")
const typeServiceRouter = require("./TypeServiceRouter")
const userRouter = require("./UserRouter")
const categoryPartRouter = require("./CategoryPartRouter")
const typePartRouter = require("./TypePartRouter")

router.use('/basket',basketRouter)
router.use('/bike',bikeRouter)
router.use('/categoryBike',categoryBikeRouter)
router.use('/categoryService',categoryServiceRouter)
router.use('/orderBike',orderBikeRouter)
router.use('/orderPart',orderPartRouter)
router.use('/orderService',orderServiceRouter)
router.use('/part',partRouter)
router.use('/service',serviceRouter)
router.use('/typeBike',typeBikeRouter)
router.use('/typeService',typeServiceRouter)
router.use('/user',userRouter)
router.use('/categoryPart',categoryPartRouter)
router.use('/categoryService',categoryServiceRouter)
router.use('/typePart',typePartRouter)

module.exports = router